# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('condition', models.CharField(choices=[(b'GOOD', b'Good'), (b'BAD', b'Bad'), (b'FAIR', b'Fair')], default=b'GOOD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Matchtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, b'First'), (2, b'Second'), (3, b'Third'), (4, b'Fourth'), (5, b'Fifth'), (6, b'Sixth'), (7, b'Seventh'), (8, b'Eighth')], default=1)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='matchtable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.Subject'),
        ),
        migrations.AddField(
            model_name='book',
            name='faculty',
            field=models.ForeignKey(default=b'NULL', on_delete=django.db.models.deletion.CASCADE, to='engineering.Faculty'),
        ),
        migrations.AddField(
            model_name='book',
            name='matchtable',
            field=models.ForeignKey(default=b'NULL', on_delete=django.db.models.deletion.CASCADE, to='engineering.Matchtable'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(default=b'NULL', on_delete=django.db.models.deletion.CASCADE, to='engineering.Subject'),
        ),
    ]
